### ISSUE TITLE
Compiles

### ISSUE THREAD

**Issue by AlexBrunetti** [Witek902/Caissa#1]
Hi,

may you release a non-AVX2/BMI version too, please? I can't run it, I'm limited to AVS and SSE.

Thanx,
Alex

**Comment by Witek902** [comment]
@AlexBrunetti I introduced non-AVX2/BMI version in [release 0.4](https://github.com/Witek902/Caissa/releases/tag/0.4). Your CPU should be able to run POPCNT version.
