### ISSUE TITLE
about the Contempt options

### ISSUE THREAD

**Issue by tissatussa** [Witek902/Caissa#13]
hi,

i just managed to compile your v1.12 on Xubuntu 22.04, AVX2 version .. i see two "contempt" options 'Static' and 'Dynamic' .. what are those ?

as i understand 'contempt' is something like 'optimism' .. i can imagine how playing style & bestmove can be different when setting such values .. maybe you even have test positions to show the effect of these options ?

**Comment by Witek902** [comment]
`StaticContempt` is regular contempt value added to the engine's eval
`DynamicContempt` is scaled based on piece count

so the final eval is calculated as follows:

```FinalEval = NeuralNetEval + StaticContempt + DynamicContempt * NumberOfPiecesOnBoard / 32```

The idea behind dynamic contempt is that if there's less pieces on the board, there's less chances of winning against weaker opponent
