### ISSUE TITLE
connection stalls in CuteChess

### ISSUE THREAD

**Issue by tissatussa** [Witek902/Caissa#3]
i let Caissa v1.3 play several games in CuteChess .. all went well but it lost the last game on time : "connection stalls" .. see screenshot. At that moment Caissa had a lost position anyway, maybe that was the cause, but it shouldn't happen. The CuteChess log did not show anything. I don't know what can be done to fix this, i just want to mention this incident.

![Caissa_v1-3_connection_stalls](https://user-images.githubusercontent.com/1109281/202655250-76c1bc28-9f3b-4165-a096-ee5d55410543.png)

**Comment by tissatussa** [comment]
again :

![Caissa_v1-3_connection_stalls2](https://user-images.githubusercontent.com/1109281/202845838-6883b171-0e75-4c03-9f0f-9a21ca9dcde5.png)

**Comment by Witek902** [comment]
@tissatussa What was the time control? Can you attach log with engine output?

**Comment by tissatussa** [comment]
i didn't save the logs of those 2 games .. therefor i just let Caissa v1.3 NNUE play again (10 min. + 3 sec bonus) with SF Kayra v1.4 noNNUE .. this time it was a very short game : after the first move Caissa failed to continue and lost again on time .. see screenshot and the ZIPped log [caissa_v1.3_stop_log.zip](https://github.com/Witek902/Caissa/files/10059148/caissa_v1.3_stop_log.zip)

in the right panes we see Kayra went to depth 36 / 37 while pondering, but Caissa stopped evaluating on depth 23 .. before these failures i had no problems with Caissa in CuteChess !? I can do more and differen tests.

![Kayra-vs-Caissa_stop](https://user-images.githubusercontent.com/1109281/203123456-b99e8736-c2e2-4a0e-8801-fd4eccef5bb5.png)

**Comment by Witek902** [comment]
OK, I managed to repro it. It's a bug with pondering (it's "Thinking on opponent's time" option in CuteChess). I'll try to fix it soon.

**Comment by tissatussa** [comment]
> ..it's "Thinking on opponent's time" option in CuteChess..

i know, indeed Caissa is pondering, CuteChess shows it.

this evening i let Caissa play another game with Black against Kayra and it had the same result : at move 32 Caissa did stop working and lost on time : "connection stalls" .. the log showed the same "stop" line.

i wonder why this happens with Caissa v1.3 (NNUE) because (as i stated) before this i never had such problem .. i hope you can solve the issue - good luck !

**Comment by tissatussa** [comment]
btw. in CuteChess i always have ponder True.

**Comment by Witek902** [comment]
@tissatussa Should be fixed on 'devel' branch now

**Comment by tissatussa** [comment]
OK, i can test it .. but help me out : how to git clone that 'devel' branch ?  It was some 'checkout' line, but how exactly ?

**Comment by Witek902** [comment]
devel branch is default branch so just sync the code

**Comment by tissatussa** [comment]
Congrats ! All seems OK !
I compiled your newest devel source .. the uci info shows a new version : "Caissa 1.3.5_pondering" .. i let this engine plays a few games, 10m+3s, with White and Black, with and without NN, always pondering ON : no "connections stalls" happened.
btw. the linux binary is only 440 Kb, compared to 3.3 Mb (!) of v1.3.0 .. i don't remember how i compiled it before, it must have the same : `cmake .` and then just `make` .. did you change the code ? Nevermind, it works.

**Comment by Witek902** [comment]
Weird, it shouldn't change size that much. Maybe you compiled different configuration (release/debug). I've seen some debug messages in your log. Try compiling with `cmake -DCMAKE_BUILD_TYPE=Release .` for best performance

**Comment by tissatussa** [comment]
i can not reproduce it : my current compiles give a binary of 374 Kb .. this is done with your tip `cmake -DCMAKE_BUILD_TYPE=Release .` .. so, it's even smaller then 440 Kb, which i get when doing just `cmake .` !

for comparison, again i did a compile of v1.3.0, using the source release ZIP .. then i got this error : 

```
/home/roelof/Compiled/Caissa-1.3_fromZIP/src/backend/Search.hpp:8:1: note: ‘std::unique_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
  7 | #include "Memory.hpp"
+++ |+#include <memory>
  8 | #include "NeuralNetworkEvaluator.hpp"
```

i don't remember this error when first compiling v1.3.0, although at that moment i used a `git clone`, not the release ZIP .. so, i added the line `#include <memory> `in Search.hpp and it works : no more error(s) and the compile went OK .. it also gives a small binary.
btw. i see you added that line in Search.hpp of the new v1.3.5 version ..

here are my ZIPped terminal logs while compiling these versions, they may help :

[caissa_v1.3_compile_release_no_error.zip](https://github.com/Witek902/Caissa/files/10071280/caissa_v1.3_compile_release_no_error.zip)
[caissa_v1.3_compile_simple.zip](https://github.com/Witek902/Caissa/files/10071281/caissa_v1.3_compile_simple.zip)
[caissa_v1.3.5_compile_release.zip](https://github.com/Witek902/Caissa/files/10071282/caissa_v1.3.5_compile_release.zip)
[caissa_v1.3_compile_release_with_memory_error.zip](https://github.com/Witek902/Caissa/files/10071283/caissa_v1.3_compile_release_with_memory_error.zip)

note: these logs contain some warnings, but the compile went OK .. should you solve these ? Would be nice :-)
