### ISSUE TITLE
how to get PNN file ?

### ISSUE THREAD

**Issue by tissatussa** [Witek902/Caissa#4]
hi, i managed to compile your newest Caissa on Linux .. the UCI info says v1.6.11 but also : _Failed to load default neural network eval-7.pnn_ .. indeed this file is missing, where to get it ?

**Comment by Witek902** [comment]
Hi, please use one included in the most recent release: https://github.com/Witek902/Caissa/releases/tag/1.6.3

**Comment by tissatussa** [comment]
thanks, i found it.
